### ISSUE TITLE
Outdated structure diagram

### ISSUE THREAD

**Issue by JanaNF** [sbsev/site#61]
The category "Beirat" is missing.

https://studenten-bilden-schueler.de/struktur

![Screen Shot 2022-07-20 at 18 24 06](https://user-images.githubusercontent.com/30958850/180112048-4e130a04-799d-4334-8009-288c8bd86a47.png)

**Comment by kleinicke** [comment]
I don't think we need to add Beirat there. Bundesvorstand in that graph stands for both the elected Bundesvorstand and the Beirat.
